### PR TITLE
Apply cargo format and fix

### PR DESCRIPTION
**Pull request by vuviettai**

### CODE REVIEW

**Comment by daywednes** [comment]
Which script is used to apply the cargo format? @vuviettai

**Comment by vuviettai** [comment]
> Which script is used to apply the cargo format? @vuviettai

@daywednes Run 2 commands 
```
cargo fmt
cargo fix
```
at the root directory. The command cargo fix removes some unused imports, others must be removed manually.

**Comment by daywednes** [comment]
this is not a scalable approach - this PR will cause confliction with other current working PRs. I'm suggesting followings:

1/ hold this PR on, and let other PRs checked in first.
2/ meanwhile, we will add cargo-husky to do linting to the whole code base and commit it in master. Other engineers will pull the new code from master, and start working with the new linting by default.

**Comment by thala321** [comment]
> this is not a scalable approach - this PR will cause confliction with other current working PRs. I'm suggesting followings:
> 
> 1/ hold this PR on, and let other PRs be checked in first.
> 2/ meanwhile, we will add cargo-husky to do linting to the whole code base and commit it in master. Other engineers will pull the new code from master, and start working with the new linting by default.

https://github.com/massbitprotocol/massbitprotocol/pull/135 This PR has the same approach as cargo husky. We can use either of them.

**Pull request closed without merging**
