### PR TITLE
ABI support

### PR DESCRIPTION
**Pull request by thala321**
- Index Manager can receive multiple ABI files (**done**)

After this PR is merged, we should pass these ABI files into Adapter so it will call to Ethereum Chain to get the Log Event

### CODE REVIEW

**Comment by thala321** [comment]
Substrate and Solana E2E Tests:
Screenshot from 2021-08-23 16-21-26

**Comment by thala321** [comment]
E2E tests:

Screenshot from 2021-08-23 16-46-21

**Comment by thala321** [comment]
Local Storage (after receiving the Index Request from Code-compiler)

Screenshot from 2021-08-23 16-54-59

**Review by anhhuy0501 — APPROVED** [review]
LGTM

**Pull request merged**
